export const SAVE = 'SAVE';
export const FIND_ALL_WIDGETS = 'FIND_ALL_WIDGETS';
export const DELETE_WIDGET = 'DELETE_WIDGETS';
export const ADD_WIDGET = 'ADD_WIDGETS';
export const HEADING_SIZE_CHANGED = 'HEADING_SIZE_CHANGED';
export const HEADING_TEXT_CHANGED = 'HEADING_TEXT_CHANGED';
export const SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE';
export const PREVIEW = 'PREVIEW';